<x-layouts.app title="Admin">
<div class="flex justify-between"><div><p class="text-orange-400">Dashboard Admin</p><h1 class="text-3xl font-black">Bakso Insight</h1></div><a href="/admin/history/print" target="_blank" class="rounded bg-white px-4 py-2 text-slate-950">Cetak riwayat</a></div>
<div class="mt-5 grid gap-4 md:grid-cols-4">@foreach($stats as $label=>$value)<div class="rounded-2xl bg-slate-900 p-5"><p class="text-slate-400">{{ $label }}</p><b class="text-2xl">{{ number_format($value) }}</b></div>@endforeach</div>
<div class="mt-5 grid gap-4 md:grid-cols-3"><div class="rounded-xl bg-slate-900 p-4">Unit paling laris<br><b>{{ $popularUnit?->name ?? 'Belum ada' }} ({{ $popularUnit?->rentals_count ?? 0 }})</b></div><div class="rounded-xl bg-slate-900 p-4">Anggota paling aktif<br><b>{{ $activeMember?->name ?? 'Belum ada' }} ({{ $activeMember?->rentals_count ?? 0 }})</b></div><div class="rounded-xl bg-slate-900 p-4">Pickup vs delivery<br><b>{{ $deliveryMix->get('pickup',0) }} : {{ $deliveryMix->get('delivery',0) }}</b></div></div>
<h2 class="mt-8 text-xl font-bold">Rental Heatmap</h2><div class="mt-3 flex flex-wrap gap-2">@forelse($heatmap as $day)<span class="rounded bg-orange-500/20 p-3">{{ $day->start_date }} · <b>{{ $day->total }}</b></span>@empty<p>Belum ada pola rental.</p>@endforelse</div>

<div class="mt-8 grid gap-6 lg:grid-cols-4">
<form method="POST" action="/admin/members" class="space-y-2 rounded-2xl bg-slate-900 p-5">@csrf<h2 class="font-bold">Tambah Anggota</h2>@foreach(['name','email','phone','address'] as $f)<input name="{{ $f }}" placeholder="{{ $f }}" class="w-full rounded bg-slate-950 p-2">@endforeach<input type="password" name="password" placeholder="password" class="w-full rounded bg-slate-950 p-2"><input type="password" name="password_confirmation" placeholder="ulangi password" class="w-full rounded bg-slate-950 p-2"><button class="rounded bg-orange-500 p-2">Simpan</button></form>
<form method="POST" action="/admin/units" class="space-y-2 rounded-2xl bg-slate-900 p-5">@csrf<h2 class="font-bold">Tambah Unit</h2>@foreach(['name','code','daily_price','max_players'] as $f)<input name="{{ $f }}" placeholder="{{ $f }}" class="w-full rounded bg-slate-950 p-2">@endforeach
@foreach($categories as $c)<label class="mr-2"><input type="checkbox" name="category_ids[]" value="{{ $c->id }}"> {{ $c->name }}</label>@endforeach<br><button class="rounded bg-orange-500 p-2">Simpan</button></form>
<form method="POST" action="/admin/categories" class="space-y-2 rounded-2xl bg-slate-900 p-5">@csrf<h2 class="font-bold">Kategori</h2><input name="name" class="w-full rounded bg-slate-950 p-2"><textarea name="description" class="w-full rounded bg-slate-950 p-2"></textarea><button class="rounded bg-orange-500 p-2">Simpan</button></form>
<form method="POST" action="/admin/combos" class="space-y-2 rounded-2xl bg-slate-900 p-5">@csrf<h2 class="font-bold">Bakso Combo</h2>@foreach(['name','duration_days','controller_count','price'] as $f)<input name="{{ $f }}" placeholder="{{ $f }}" class="w-full rounded bg-slate-950 p-2">@endforeach<button class="rounded bg-orange-500 p-2">Simpan</button></form></div>

<h2 class="mt-8 text-xl font-bold">Anggota</h2><div class="mt-3 grid gap-3 md:grid-cols-2">@forelse($members as $m)<form method="POST" action="/admin/members/{{ $m->id }}" class="rounded-xl bg-slate-900 p-4">@csrf @method('PUT')<input name="name" value="{{ $m->name }}" class="rounded bg-slate-950 p-2"><input name="email" value="{{ $m->email }}" class="rounded bg-slate-950 p-2"><input name="phone" value="{{ $m->profile?->phone }}" class="rounded bg-slate-950 p-2"><input name="address" value="{{ $m->profile?->address }}" class="rounded bg-slate-950 p-2"><button class="mt-2 text-orange-400">Update</button><button formmethod="POST" formaction="/admin/members/{{ $m->id }}" name="_method" value="DELETE" class="ml-4 text-red-400">Hapus</button></form>@empty<p>Belum ada anggota.</p>@endforelse</div>

<h2 class="mt-8 text-xl font-bold">Booking</h2><div class="mt-3 space-y-2">@forelse($bookings as $b)<div class="flex justify-between rounded-xl bg-slate-900 p-4"><span>{{ $b->user->name }} · {{ $b->unit->name }} · {{ $b->status->value }}</span><div class="flex gap-3"><form method="POST" action="/admin/bookings/{{ $b->id }}/confirm">@csrf<button>Konfirmasi</button></form><form method="POST" action="/admin/bookings/{{ $b->id }}/start">@csrf<button class="text-orange-400">Mulai Rental</button></form></div></div>@empty<p>Belum ada booking.</p>@endforelse</div>

<h2 class="mt-8 text-xl font-bold">Rental, Return & Transaksi</h2><div class="mt-3 space-y-3">@forelse($rentals as $r)<div class="rounded-xl bg-slate-900 p-4"><b>{{ $r->rental_code }} · {{ $r->user->name }} · {{ $r->unit->name }}</b><div class="mt-3 flex flex-wrap gap-4"><form method="POST" action="/admin/rentals/{{ $r->id }}/return">@csrf<input type="date" name="returned_at" value="{{ today()->toDateString() }}" class="rounded bg-slate-950 p-2"><input name="daily_fine" placeholder="denda/hari" class="w-28 rounded bg-slate-950 p-2"><button class="text-orange-400">Proses kembali</button></form><form method="POST" action="/admin/rentals/{{ $r->id }}/fines">@csrf<input name="amount" placeholder="denda rusak" class="w-28 rounded bg-slate-950 p-2"><input name="reason" placeholder="alasan" class="rounded bg-slate-950 p-2"><button>Tambah denda</button></form>@if($r->transaction && $r->transaction->status->value !== 'paid')<form method="POST" action="/admin/transactions/{{ $r->transaction->id }}/pay">@csrf<button class="rounded bg-emerald-500 p-2">Konfirmasi bayar</button></form>@endif</div>@foreach($r->extensions as $e)@if($e->status->value === 'pending')<form method="POST" action="/admin/extensions/{{ $e->id }}" class="mt-2">@csrfPerpanjangan sampai {{ $e->requested_due_date->format('d/m/Y') }} <button name="status" value="approved" class="text-emerald-400">Setujui</button> · <button name="status" value="rejected" class="text-red-400">Tolak</button></form>@endif @endforeach</div>@empty<p>Belum ada rental.</p>@endforelse</div>

<h2 class="mt-8 text-xl font-bold">Pickup & Delivery</h2><div class="mt-3 space-y-3">@forelse($deliveries as $d)<form method="POST" action="/admin/deliveries/{{ $d->id }}" class="grid gap-2 rounded-xl bg-slate-900 p-4 md:grid-cols-5">@csrf<span>{{ $d->rental->user->name }} · {{ $d->type->value }}</span><select name="status" class="rounded bg-slate-950 p-2">@foreach(App\Enums\DeliveryStatus::cases() as $s)<option value="{{ $s->value }}" @selected($d->status === $s)>{{ $s->value }}</option>@endforeach</select><input name="courier_name" value="{{ $d->courier_name }}" placeholder="kurir" class="rounded bg-slate-950 p-2"><input name="delivery_fee" value="{{ $d->delivery_fee }}" class="rounded bg-slate-950 p-2"><button class="text-orange-400">Update layanan</button></form>@empty<p>Belum ada layanan delivery.</p>@endforelse</div>
</x-layouts.app>
